version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ##N3wt3lco##
        port: 4466
        databases:
          default:
            connector: mysql
            host: 94.249.131.5
            port: 3306
            user: ntvaca
            database: ntvacations
            password: "##N3wt3lco##"
            connectionLimit: 5
