version: '3.1'

services:
  web:
    ports:
      - 7000:3000
    build: .
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
      - ./serviceacct.json:/usr/src/app/serviceacct.json
